"""add_subscription_plans_table

Revision ID: 415cf7ae567a
Revises: de506a759552
Create Date: 2026-04-17 13:50:29.419611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415cf7ae567a'
down_revision: Union[str, Sequence[str], None] = 'de506a759552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_yearly', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id_monthly', sa.Text(), nullable=True),
    sa.Column('stripe_price_id_yearly', sa.Text(), nullable=True),
    sa.Column('max_workspaces', sa.Integer(), nullable=False),
    sa.Column('max_projects_per_workspace', sa.Integer(), nullable=False),
    sa.Column('max_members_per_workspace', sa.Integer(), nullable=False),
    sa.Column('max_members_per_project', sa.Integer(), nullable=False),
    sa.Column('max_storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('can_use_4d', sa.Boolean(), nullable=False),
    sa.Column('can_use_5d', sa.Boolean(), nullable=False),
    sa.Column('can_use_clash_detection', sa.Boolean(), nullable=False),
    sa.Column('can_export_bcf', sa.Boolean(), nullable=False),
    sa.Column('can_use_ai', sa.Boolean(), nullable=False),
    sa.Column('can_use_maintenance', sa.Boolean(), nullable=False),
    sa.Column('can_use_facility', sa.Boolean(), nullable=False),
    sa.Column('can_use_api', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
