"""initial 2

Revision ID: de506a759552
Revises: de59b09524e0
Create Date: 2026-04-05 23:35:25.171685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de506a759552'
down_revision: Union[str, Sequence[str], None] = 'de59b09524e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aim_project_members', sa.Column('is_share_only', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('aim_project_members', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('pim_project_members', sa.Column('is_share_only', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('pim_project_members', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pim_project_members', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('pim_project_members', 'is_share_only')
    op.alter_column('aim_project_members', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('aim_project_members', 'is_share_only')
    # ### end Alembic commands ###
